[Unit]
Description=EdgeSync Django ASGI Application
After=network.target

[Service]
Type=exec
User=www-data
Group=www-data
WorkingDirectory=/var/www/app/edgesync
Environment=PATH=/var/www/app/edgesync/venv/bin
EnvironmentFile=/var/www/app/edgesync/.env
# Verbose logging with access log
ExecStart=/var/www/app/edgesync/venv/bin/daphne -b 127.0.0.1 -p 8000 --access-log /var/www/app/edgesync/logs/daphne_access.log --verbosity 2 edgesync.asgi:application
ExecReload=/bin/kill -s HUP $MAINPID
KillMode=mixed
TimeoutStopSec=5
PrivateTmp=true
Restart=always
RestartSec=3

# Logging
StandardOutput=journal
StandardError=journal
SyslogIdentifier=edgesync

[Install]
WantedBy=multi-user.target