# Generated by Django 5.1.5 on 2025-05-26 06:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        help_text="Unique identifier for the ESP32 device",
                        max_length=100,
                    ),
                ),
                (
                    "sensor_type",
                    models.CharField(
                        help_text="Type of sensor (e.g., temperature, humidity, pressure)",
                        max_length=50,
                    ),
                ),
                ("value", models.FloatField(help_text="Sensor reading value")),
                (
                    "unit",
                    models.CharField(
                        blank=True, help_text="Unit of measurement", max_length=20
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the data was received",
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True, help_text="Original JSON data from ESP32", null=True
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device_id", "-timestamp"],
                        name="sensors_sen_device__64c3d5_idx",
                    ),
                    models.Index(
                        fields=["sensor_type", "-timestamp"],
                        name="sensors_sen_sensor__76c9ac_idx",
                    ),
                ],
            },
        ),
    ]
