# Generated by Django 4.2.7 on 2026-01-16 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human readable device name", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Device description"),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="Unique authentication token for device",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("offline", "Offline"),
                            ("error", "Error"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        blank=True,
                        help_text="When device was last seen online",
                        null=True,
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True, help_text="Legacy device identifier", max_length=100
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True, help_text="Legacy tenant identifier", max_length=100
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        blank=True, help_text="Type of device", max_length=50
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether device is active"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "devices",
            },
        ),
        migrations.CreateModel(
            name="MosquittoACL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("topic", models.TextField(help_text="MQTT topic pattern")),
                (
                    "rw",
                    models.IntegerField(
                        choices=[
                            (1, "Read"),
                            (2, "Write"),
                            (3, "Read/Write"),
                            (4, "Subscribe"),
                        ],
                        help_text="Read/Write permissions",
                    ),
                ),
            ],
            options={
                "db_table": "mosquitto_acls",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="MosquittoSuperuser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("is_superuser", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "mosquitto_superusers",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="MosquittoUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("password", models.TextField(help_text="PBKDF2 hashed password")),
            ],
            options={
                "db_table": "mosquitto_users",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="MqttActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("publish", "Message Published"),
                            ("subscribe", "Topic Subscribed"),
                            ("unsubscribe", "Topic Unsubscribed"),
                            ("connect", "Client Connected"),
                            ("disconnect", "Client Disconnected"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "topic_name",
                    models.CharField(
                        blank=True, help_text="Associated topic", max_length=255
                    ),
                ),
                (
                    "client_id",
                    models.CharField(
                        blank=True, help_text="MQTT client ID", max_length=255
                    ),
                ),
                (
                    "message_size",
                    models.IntegerField(
                        blank=True, help_text="Message size in bytes", null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "mqtt_activities",
            },
        ),
        migrations.CreateModel(
            name="MqttCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for the cluster", max_length=200
                    ),
                ),
                (
                    "cluster_type",
                    models.CharField(
                        choices=[
                            ("hosted", "Hosted by EdgeSync"),
                            ("external", "External/Third-party"),
                        ],
                        default="external",
                        max_length=20,
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        help_text="MQTT broker hostname/IP", max_length=255
                    ),
                ),
                (
                    "port",
                    models.IntegerField(default=1883, help_text="MQTT broker port"),
                ),
                (
                    "use_ssl",
                    models.BooleanField(
                        default=False, help_text="Use SSL/TLS connection"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, help_text="MQTT username", max_length=100
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        help_text="MQTT password (encrypted)",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Cluster description"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether cluster is active"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "total_topics",
                    models.IntegerField(default=0, help_text="Number of active topics"),
                ),
                (
                    "total_messages",
                    models.BigIntegerField(
                        default=0, help_text="Total messages published"
                    ),
                ),
                (
                    "total_subscriptions",
                    models.IntegerField(
                        default=0, help_text="Number of active subscriptions"
                    ),
                ),
            ],
            options={
                "db_table": "mqtt_clusters",
            },
        ),
        migrations.CreateModel(
            name="MqttTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic_name",
                    models.CharField(help_text="MQTT topic name", max_length=255),
                ),
                (
                    "message_count",
                    models.BigIntegerField(
                        default=0, help_text="Total messages on this topic"
                    ),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When last message was received",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "mqtt_topics",
            },
        ),
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        help_text="Unique identifier for the ESP32 device",
                        max_length=100,
                    ),
                ),
                (
                    "sensor_type",
                    models.CharField(
                        help_text="Type of sensor (e.g., temperature, humidity, pressure)",
                        max_length=50,
                    ),
                ),
                ("value", models.FloatField(help_text="Sensor reading value")),
                (
                    "unit",
                    models.CharField(
                        blank=True, help_text="Unit of measurement", max_length=20
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the data was received",
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True, help_text="Original JSON data from ESP32", null=True
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="TrackedVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=100)),
                ("sensor_type", models.CharField(max_length=50)),
                ("widget_id", models.CharField(max_length=100)),
                ("dashboard_uuid", models.CharField(max_length=36)),
                (
                    "max_samples",
                    models.IntegerField(
                        default=50, help_text="How many samples to retain"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tracked_variables",
            },
        ),
        migrations.CreateModel(
            name="WidgetSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("value", models.FloatField()),
                ("unit", models.CharField(blank=True, max_length=20)),
                (
                    "widget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="sensors.trackedvariable",
                    ),
                ),
            ],
            options={
                "db_table": "widget_samples",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserACL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic_pattern",
                    models.TextField(
                        help_text="MQTT topic pattern (e.g., iot/tenant_001/+/+)"
                    ),
                ),
                (
                    "access_type",
                    models.IntegerField(
                        choices=[
                            (1, "Read"),
                            (2, "Write"),
                            (3, "Read/Write"),
                            (4, "Subscribe"),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mqtt_acls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_acls",
                "managed": True,
            },
        ),
        migrations.AddIndex(
            model_name="trackedvariable",
            index=models.Index(
                fields=["device_id", "sensor_type"],
                name="tracked_var_device__81a43e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trackedvariable",
            index=models.Index(
                fields=["widget_id"], name="tracked_var_widget__29f6cf_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trackedvariable",
            unique_together={("device_id", "sensor_type", "widget_id")},
        ),
        migrations.AddIndex(
            model_name="sensordata",
            index=models.Index(
                fields=["device_id", "-timestamp"],
                name="sensors_sen_device__64c3d5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sensordata",
            index=models.Index(
                fields=["sensor_type", "-timestamp"],
                name="sensors_sen_sensor__76c9ac_idx",
            ),
        ),
        migrations.AddField(
            model_name="mqtttopic",
            name="cluster",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="sensors.mqttcluster",
            ),
        ),
        migrations.AddField(
            model_name="mqttcluster",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this cluster belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.organization",
            ),
        ),
        migrations.AddField(
            model_name="mqttcluster",
            name="user",
            field=models.ForeignKey(
                help_text="Cluster owner",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mqttactivity",
            name="cluster",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="sensors.mqttcluster",
            ),
        ),
        migrations.AddField(
            model_name="mosquittouser",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mosquittoacl",
            unique_together={("username", "topic", "rw")},
        ),
        migrations.AddField(
            model_name="device",
            name="creator",
            field=models.ForeignKey(
                help_text="Device creator",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_devices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="organization",
            field=models.ForeignKey(
                help_text="Organization this device belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="user.organization",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="projects",
            field=models.ManyToManyField(
                blank=True,
                help_text="Projects this device is assigned to",
                related_name="devices",
                to="user.project",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="user",
            field=models.ForeignKey(
                help_text="Legacy device owner",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legacy_devices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="widgetsample",
            index=models.Index(
                fields=["widget", "-timestamp"], name="widget_samp_widget__907f9c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="useracl",
            unique_together={("user", "topic_pattern", "access_type")},
        ),
        migrations.AddIndex(
            model_name="mqtttopic",
            index=models.Index(
                fields=["cluster", "-last_message_at"],
                name="mqtt_topics_cluster_42257c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mqtttopic",
            index=models.Index(
                fields=["cluster", "is_active"], name="mqtt_topics_cluster_2fe3e2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mqtttopic",
            unique_together={("cluster", "topic_name")},
        ),
        migrations.AddIndex(
            model_name="mqttcluster",
            index=models.Index(
                fields=["user", "-created_at"], name="mqtt_cluste_user_id_b4ab27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mqttcluster",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="mqtt_cluste_organiz_08c7b4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mqttcluster",
            index=models.Index(
                fields=["cluster_type", "is_active"],
                name="mqtt_cluste_cluster_ccac77_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mqttactivity",
            index=models.Index(
                fields=["cluster", "-timestamp"], name="mqtt_activi_cluster_c3bf85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mqttactivity",
            index=models.Index(
                fields=["activity_type", "-timestamp"],
                name="mqtt_activi_activit_31f779_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mqttactivity",
            index=models.Index(
                fields=["cluster", "topic_name", "-timestamp"],
                name="mqtt_activi_cluster_8e1125_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="devices_organiz_c9aa6d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["creator", "-created_at"], name="devices_creator_a7b52c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["uuid"], name="devices_uuid_3c44ba_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["token"], name="devices_token_fa5a84_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["status", "is_active"], name="devices_status_4d9558_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["user", "tenant_id"], name="devices_user_id_da3f04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["device_id"], name="devices_device__c4b5e4_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="device",
            unique_together={("organization", "name")},
        ),
    ]
