# Generated by Django 5.1.5 on 2025-06-07 13:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MosquittoSuperuser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("is_superuser", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "mosquitto_superusers",
            },
        ),
        migrations.CreateModel(
            name="MosquittoACL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("topic", models.TextField(help_text="MQTT topic pattern")),
                (
                    "rw",
                    models.IntegerField(
                        choices=[
                            (1, "Read"),
                            (2, "Write"),
                            (3, "Read/Write"),
                            (4, "Subscribe"),
                        ],
                        help_text="Read/Write permissions",
                    ),
                ),
            ],
            options={
                "db_table": "mosquitto_acls",
                "unique_together": {("username", "topic", "rw")},
            },
        ),
        migrations.CreateModel(
            name="MosquittoUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("password", models.TextField(help_text="PBKDF2 hashed password")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mosquitto_users",
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        help_text="Unique device identifier",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        help_text="Human readable device name", max_length=200
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(help_text="Tenant identifier", max_length=100),
                ),
                (
                    "device_type",
                    models.CharField(help_text="Type of device", max_length=50),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether device is active"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Device owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "devices",
                "indexes": [
                    models.Index(
                        fields=["user", "tenant_id"], name="devices_user_id_da3f04_idx"
                    ),
                    models.Index(
                        fields=["device_id"], name="devices_device__c4b5e4_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserACL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic_pattern",
                    models.TextField(
                        help_text="MQTT topic pattern (e.g., iot/tenant_001/+/+)"
                    ),
                ),
                (
                    "access_type",
                    models.IntegerField(
                        choices=[
                            (1, "Read"),
                            (2, "Write"),
                            (3, "Read/Write"),
                            (4, "Subscribe"),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_acls",
                "unique_together": {("user", "topic_pattern", "access_type")},
            },
        ),
    ]
