# Generated by Django 5.1.5 on 2025-06-07 16:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0003_delete_mosquittoacl_delete_mosquittosuperuser_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        help_text="Unique device identifier",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        help_text="Human readable device name", max_length=200
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(help_text="Tenant identifier", max_length=100),
                ),
                (
                    "device_type",
                    models.CharField(help_text="Type of device", max_length=50),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether device is active"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Device owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "devices",
                "indexes": [
                    models.Index(
                        fields=["user", "tenant_id"], name="devices_user_id_da3f04_idx"
                    ),
                    models.Index(
                        fields=["device_id"], name="devices_device__c4b5e4_idx"
                    ),
                ],
            },
        ),
    ]
