# Generated by Django 4.2.7 on 2025-06-15 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_organization_dashboardtemplate_templatepermission_and_more"),
        ("sensors", "0004_auto_20250607_1611"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this device belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="devices_organiz_c9aa6d_idx",
            ),
        ),
    ]
