# Generated by Django 4.2.7 on 2025-07-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_project_dashboardtemplate_project"),
        ("sensors", "0008_device_management"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="device",
            name="unique_device_name_per_org",
        ),
        migrations.RemoveIndex(
            model_name="device",
            name="sensors_device_org_created_idx",
        ),
        migrations.RenameIndex(
            model_name="device",
            new_name="devices_creator_a7b52c_idx",
            old_name="sensors_device_creator_created_idx",
        ),
        migrations.RenameIndex(
            model_name="device",
            new_name="devices_uuid_3c44ba_idx",
            old_name="sensors_device_uuid_idx",
        ),
        migrations.RenameIndex(
            model_name="device",
            new_name="devices_token_fa5a84_idx",
            old_name="sensors_device_token_idx",
        ),
        migrations.RenameIndex(
            model_name="device",
            new_name="devices_status_4d9558_idx",
            old_name="sensors_device_status_active_idx",
        ),
        migrations.AlterField(
            model_name="device",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("offline", "Offline"),
                    ("error", "Error"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="device",
            unique_together={("organization", "name")},
        ),
    ]
