# Generated by Django 4.2.7 on 2025-07-09 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0009_remove_device_unique_device_name_per_org_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackedVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=100)),
                ("sensor_type", models.CharField(max_length=50)),
                ("widget_id", models.CharField(max_length=100)),
                ("dashboard_uuid", models.CharField(max_length=36)),
                (
                    "max_samples",
                    models.IntegerField(
                        default=50, help_text="How many samples to retain"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tracked_variables",
            },
        ),
        migrations.CreateModel(
            name="WidgetSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("value", models.FloatField()),
                ("unit", models.CharField(blank=True, max_length=20)),
                (
                    "widget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="sensors.trackedvariable",
                    ),
                ),
            ],
            options={
                "db_table": "widget_samples",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="trackedvariable",
            index=models.Index(
                fields=["device_id", "sensor_type"],
                name="tracked_var_device__81a43e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trackedvariable",
            index=models.Index(
                fields=["widget_id"], name="tracked_var_widget__29f6cf_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trackedvariable",
            unique_together={("device_id", "sensor_type", "widget_id")},
        ),
        migrations.AddIndex(
            model_name="widgetsample",
            index=models.Index(
                fields=["widget", "-timestamp"], name="widget_samp_widget__907f9c_idx"
            ),
        ),
    ]
