# Generated by Django 4.2.7 on 2026-01-16 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowDiagram",
            fields=[
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("nodes", models.JSONField(default=list)),
                ("edges", models.JSONField(default=list)),
                ("metadata", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.CharField(default="1.0.0", max_length=20)),
                ("tags", models.JSONField(default=list)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flows",
                        to="user.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="FlowExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("stopped", "Stopped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("result", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True)),
                (
                    "flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flows.flowdiagram",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NodeExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_id", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("input_data", models.JSONField(default=dict)),
                ("output_data", models.JSONField(default=dict)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(default=0)),
                (
                    "flow_execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flows.flowexecution",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FlowNodeOutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_id", models.CharField(max_length=100)),
                ("output_data", models.JSONField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "flow_execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_outputs",
                        to="flows.flowexecution",
                    ),
                ),
            ],
            options={
                "db_table": "flow_node_outputs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["flow_execution", "node_id", "-timestamp"],
                        name="flow_node_o_flow_ex_e1e6ed_idx",
                    ),
                    models.Index(
                        fields=["node_id", "-timestamp"],
                        name="flow_node_o_node_id_402921_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("dashboard_template_uuid", models.CharField(max_length=36)),
                ("widget_id", models.CharField(max_length=100)),
                (
                    "data_source_type",
                    models.CharField(
                        choices=[
                            ("flow_node", "Flow Node Output"),
                            ("device_sensor", "Device Sensor"),
                            ("static", "Static Data"),
                        ],
                        default="flow_node",
                        max_length=20,
                    ),
                ),
                ("node_id", models.CharField(blank=True, max_length=100)),
                ("output_field", models.CharField(default="output", max_length=100)),
                ("auto_refresh", models.BooleanField(default=True)),
                ("refresh_interval", models.IntegerField(default=30000)),
                ("data_transform", models.TextField(blank=True)),
                (
                    "aggregation_type",
                    models.CharField(
                        choices=[
                            ("last", "Latest Value"),
                            ("avg", "Average"),
                            ("sum", "Sum"),
                            ("count", "Count"),
                            ("min", "Minimum"),
                            ("max", "Maximum"),
                        ],
                        default="last",
                        max_length=20,
                    ),
                ),
                ("widget_title", models.CharField(max_length=200)),
                ("widget_type", models.CharField(max_length=50)),
                ("widget_config", models.JSONField(default=dict)),
                ("grid_position", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "flow",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flows.flowdiagram",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_widgets",
                "indexes": [
                    models.Index(
                        fields=["dashboard_template_uuid"],
                        name="dashboard_w_dashboa_094309_idx",
                    ),
                    models.Index(
                        fields=["flow", "node_id"],
                        name="dashboard_w_flow_id_bce31e_idx",
                    ),
                    models.Index(
                        fields=["data_source_type"],
                        name="dashboard_w_data_so_6fb6dd_idx",
                    ),
                ],
                "unique_together": {("dashboard_template_uuid", "widget_id")},
            },
        ),
    ]
