# Generated by Django 4.2.7 on 2025-06-16 06:49

from django.db import migrations, models
import uuid


def populate_uuid(apps, schema_editor):
    FlowDiagram = apps.get_model('flows', 'FlowDiagram')
    for flow in FlowDiagram.objects.filter(uuid__isnull=True):
        flow.uuid = uuid.uuid4()
        flow.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0001_initial"),
    ]

    operations = [
        # Step 1: add nullable field without unique constraint
        migrations.AddField(
            model_name='flowdiagram',
            name='uuid',
            field=models.UUIDField(null=True, editable=False),
        ),
        # Step 2: populate existing rows
        migrations.RunPython(populate_uuid, migrations.RunPython.noop),
        # Step 3: make field required and unique with default for new rows
        migrations.AlterField(
            model_name='flowdiagram',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
