# Generated by Django 4.2.7 on 2025-06-19 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_project_dashboardtemplate_project"),
        ("flows", "0002_flowdiagram_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowdiagram",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flows",
                to="user.project",
            ),
        ),
    ]
