# Generated by Django 4.2.7 on 2026-01-16 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Organization name", max_length=200),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Organization description"),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly organization identifier",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether organization is active"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Organization owner/creator",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_organizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subscription_type",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("freemium", "Freemium"),
                            ("paid", "Paid"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "mqtt_username",
                    models.CharField(
                        blank=True,
                        help_text="Generated MQTT username",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "mqtt_password_set",
                    models.BooleanField(
                        default=False, help_text="Whether user has set MQTT password"
                    ),
                ),
                (
                    "mqtt_connected",
                    models.BooleanField(
                        default=False,
                        help_text="Whether user is connected to MQTT broker",
                    ),
                ),
                (
                    "device_limit",
                    models.IntegerField(
                        default=5, help_text="Maximum number of devices allowed"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_profiles",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(help_text="Project name", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Project description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        default=list, help_text="Project tags for categorization"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Additional project metadata"
                    ),
                ),
                (
                    "auto_save",
                    models.BooleanField(
                        default=True, help_text="Auto-save flow changes"
                    ),
                ),
                (
                    "data_retention_days",
                    models.IntegerField(
                        default=30, help_text="Data retention period in days"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="user.organization",
                    ),
                ),
            ],
            options={
                "db_table": "projects",
                "ordering": ["-updated_at"],
                "unique_together": {("organization", "name")},
            },
        ),
        migrations.CreateModel(
            name="PasswordResetOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="User email for password reset", max_length=254
                    ),
                ),
                ("otp", models.CharField(help_text="6-digit OTP code", max_length=6)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(help_text="OTP expiration time")),
                (
                    "is_used",
                    models.BooleanField(
                        default=False, help_text="Whether OTP has been used"
                    ),
                ),
                (
                    "attempts",
                    models.IntegerField(
                        default=0, help_text="Number of verification attempts"
                    ),
                ),
            ],
            options={
                "db_table": "password_reset_otps",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "-created_at"],
                        name="password_re_email_f96675_idx",
                    ),
                    models.Index(
                        fields=["otp", "email"], name="password_re_otp_696acb_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DashboardTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(help_text="Template name", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Template description"),
                ),
                (
                    "layout",
                    models.JSONField(
                        default=dict, help_text="Dashboard layout configuration"
                    ),
                ),
                (
                    "widgets",
                    models.JSONField(
                        default=list, help_text="Dashboard widgets configuration"
                    ),
                ),
                (
                    "datasources",
                    models.JSONField(default=list, help_text="Connected datasources"),
                ),
                (
                    "update_frequency",
                    models.IntegerField(
                        default=30, help_text="Update frequency in seconds"
                    ),
                ),
                (
                    "connection_timeout",
                    models.IntegerField(
                        default=10, help_text="Database connection timeout in seconds"
                    ),
                ),
                (
                    "flow_config",
                    models.JSONField(
                        default=dict, help_text="Associated flow configuration"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_templates",
                        to="user.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_templates",
                        to="user.project",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_templates",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="TemplatePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission_type",
                    models.CharField(
                        choices=[("admin", "Admin"), ("user", "User")],
                        default="user",
                        max_length=10,
                    ),
                ),
                ("granted_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "granted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="granted_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="user.dashboardtemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "template_permissions",
                "ordering": ["granted_at"],
                "unique_together": {("template", "user")},
            },
        ),
        migrations.CreateModel(
            name="OrganizationMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("user", "User")],
                        default="user",
                        max_length=10,
                    ),
                ),
                ("joined_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="user.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "organization_members",
                "ordering": ["joined_at"],
                "unique_together": {("organization", "user")},
            },
        ),
        migrations.CreateModel(
            name="DeviceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(help_text="Device identifier", max_length=100),
                ),
                (
                    "device_name",
                    models.CharField(
                        help_text="Device name at time of action", max_length=200
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Device Created"),
                            ("updated", "Device Updated"),
                            ("deleted", "Device Deleted"),
                            ("connected", "Device Connected"),
                            ("disconnected", "Device Disconnected"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True, help_text="Additional action details", null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "device_history",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="device_hist_user_id_002b0d_idx",
                    ),
                    models.Index(
                        fields=["device_id", "-timestamp"],
                        name="device_hist_device__72079e_idx",
                    ),
                ],
            },
        ),
    ]
