# Generated by Django 4.2.7 on 2025-06-16 06:49

from django.db import migrations, models
import uuid


def populate_uuid(apps, schema_editor):
    DashboardTemplate = apps.get_model('user', 'DashboardTemplate')
    for template in DashboardTemplate.objects.filter(uuid__isnull=True):
        template.uuid = uuid.uuid4()
        template.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_organization_dashboardtemplate_templatepermission_and_more"),
    ]

    operations = [
        # Step 1: add nullable non-unique field
        migrations.AddField(
            model_name="dashboardtemplate",
            name="uuid",
            field=models.UUIDField(null=True, editable=False),
        ),
        # Step 2: populate existing rows
        migrations.RunPython(populate_uuid, migrations.RunPython.noop),
        # Step 3: set default, unique and non-null
        migrations.AlterField(
            model_name="dashboardtemplate",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
