# Generated by Django 4.2.7 on 2025-06-19 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0003_dashboardtemplate_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(help_text="Project name", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Project description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        default=list, help_text="Project tags for categorization"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Additional project metadata"
                    ),
                ),
                (
                    "auto_save",
                    models.BooleanField(
                        default=True, help_text="Auto-save flow changes"
                    ),
                ),
                (
                    "data_retention_days",
                    models.IntegerField(
                        default=30, help_text="Data retention period in days"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="user.organization",
                    ),
                ),
            ],
            options={
                "db_table": "projects",
                "ordering": ["-updated_at"],
                "unique_together": {("organization", "name")},
            },
        ),
        migrations.AddField(
            model_name="dashboardtemplate",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dashboard_templates",
                to="user.project",
            ),
        ),
    ]
