# Generated by Django 4.2.7 on 2025-10-05 03:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_project_dashboardtemplate_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="User email for password reset", max_length=254
                    ),
                ),
                ("otp", models.CharField(help_text="6-digit OTP code", max_length=6)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(help_text="OTP expiration time")),
                (
                    "is_used",
                    models.BooleanField(
                        default=False, help_text="Whether OTP has been used"
                    ),
                ),
                (
                    "attempts",
                    models.IntegerField(
                        default=0, help_text="Number of verification attempts"
                    ),
                ),
            ],
            options={
                "db_table": "password_reset_otps",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "-created_at"],
                        name="password_re_email_f96675_idx",
                    ),
                    models.Index(
                        fields=["otp", "email"], name="password_re_otp_696acb_idx"
                    ),
                ],
            },
        ),
    ]
